- hosts: backend
  become: true

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Remove existing application repository
      file:
        path: /home/ubuntu/two-tier-ansible-jenkins-CICD
        state: absent

    - name: Clone two-tier application repository
      git:
        repo: https://github.com/farhaz1449/two-tier-ansible-jenkins-CICD.git
        dest: /home/ubuntu/two-tier-ansible-jenkins-CICD

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - python3-flask
        - npm

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: Install backend dependencies
      command: pip3 install -r requirements.txt
      args:
        chdir: /home/ubuntu/two-tier-ansible-jenkins-CICD/backend

    - name: Stop existing backend process if running
      command: pm2 delete backend
      ignore_errors: yes

    - name: Start backend application
      command: pm2 start --name backend "flask run --host=0.0.0.0"
      args:
        chdir: /home/ubuntu/two-tier-ansible-jenkins-CICD/backend
      environment:
        FLASK_APP: app.py
        FLASK_ENV: production

